
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { SidebarWrapper } from "@/components/SidebarWrapper";
import { SidebarProvider } from "@/components/ui/sidebar";
import SessionProvider from "@/components/SessionProvider";
import { Toaster } from "@/components/ui/toaster";
import { MobileSidebarToggle } from "@/components/MobileSidebarToggle";
import { ThemeProvider } from "@/components/theme-provider";
import { ThemeScript } from "@/components/ThemeScript";
import { ThemeModeProvider, DEFAULT_THEME } from "@/components/providers/ThemeSettingsProvider";
import { getCurrentUser } from "@/lib/auth";
import { prisma } from "@/lib/prisma";

export const dynamic = 'force-dynamic';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentUser();

  let themeMode: 'light' | 'dark' | 'system' = DEFAULT_THEME.mode;

  if (user) {
    const userTheme = await prisma.userTheme.findUnique({
      where: { userId: user.id }
    });

    if (userTheme && userTheme.mode) {
      const validModes = ['light', 'dark', 'system'] as const;
      themeMode = validModes.includes(userTheme.mode as 'light' | 'dark' | 'system') 
        ? userTheme.mode as 'light' | 'dark' | 'system' 
        : 'system';
    }
  }

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme={themeMode}
            enableSystem
            disableTransitionOnChange
            storageKey="safcha-theme-v2"
          >
            <ThemeModeProvider initialMode={themeMode}>
              <ThemeScript />
              <SidebarProvider>
                <SidebarWrapper user={user} />
                <main className="flex-1 min-h-screen bg-background text-foreground w-full">
                  <div className="p-4 lg:hidden">
                    <MobileSidebarToggle />
                  </div>
                  {children}
                </main>
              </SidebarProvider>
              <Toaster />
            </ThemeModeProvider>
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
