import {
    FaHome, FaUser, FaCog, FaChartBar, FaShoppingCart, FaBox, FaFileAlt,
    FaUsers, FaShieldAlt, FaLock, FaUnlock, FaKey, FaBell, FaSearch,
    FaCalendar, FaClock, FaEnvelope, FaPhone, FaMapMarkerAlt, FaCamera,
    FaImage, FaVideo, FaMusic, FaPlay, FaPause, FaStop, FaStar, FaHeart,
    FaThumbsUp, FaThumbsDown, FaCheck, FaTimes, FaPlus, FaMinus, FaEquals,
    FaArrowRight, FaArrowLeft, FaArrowUp, FaArrowDown, FaChevronRight,
    FaChevronLeft, FaChevronUp, FaChevronDown, FaBars, FaEllipsisH,
    FaEllipsisV, FaTrash, FaEdit, FaSave, FaDownload, FaUpload, FaShare,
    FaExternalLinkAlt, FaLink, FaUnlink, FaGlobe, FaWifi, FaBatteryFull,
    FaDesktop, FaLaptop, FaMobileAlt, FaTabletAlt, FaTv, FaBook, FaBookmark,
    FaBriefcase, FaBuilding, FaCar, FaTruck, FaPlane, FaShip, FaSubway,
    FaTrain, FaBicycle, FaWalking, FaWheelchair, FaBed, FaHotel, FaCoffee,
    FaUtensils, FaBeer, FaGlassCheers, FaBirthdayCake, FaGift, FaTrophy,
    FaMedal, FaCrown, FaMoneyBill, FaCreditCard, FaWallet, FaDollarSign,
    // New Business Icons
    FaHandshake, FaChartLine, FaChartPie, FaChartArea, FaBalanceScale,
    FaBullhorn, FaBullseye, FaCalculator, FaCalendarCheck, FaCalendarPlus,
    FaCertificate, FaClipboard, FaClipboardList, FaClipboardCheck, FaCoins,
    FaComment, FaCommentDots, FaComments, FaCompass, FaCopy, FaCopyright,
    FaDatabase, FaDirections, FaFile, FaFileArchive, FaFileAudio, FaFileCode,
    FaFileContract, FaFileCsv, FaFileDownload, FaFileExcel, FaFileExport,
    FaFileImage, FaFileImport, FaFileInvoice, FaFileInvoiceDollar, FaFilePdf,
    FaFilePowerpoint, FaFilePrescription, FaFileSignature, FaFileUpload,
    FaFileVideo, FaFileWord, FaFingerprint, FaFlag, FaFolder, FaFolderOpen,
    FaFolderPlus, FaFolderMinus, FaGavel, FaGem, FaGlobeAmericas, FaGlobeAsia,
    FaGlobeEurope, FaHeadset, FaHistory, FaHourglass, FaHourglassEnd,
    FaHourglassHalf, FaHourglassStart, FaIdBadge, FaIdCard, FaImage as FaImage2,
    FaInbox, FaIndustry, FaInfo, FaInfoCircle, FaKey as FaKey2, FaKeyboard,
    FaLandmark, FaLayerGroup, FaLeaf, FaList, FaListAlt, FaListOl, FaListUl,
    FaMap, FaMapMarked, FaMapMarkedAlt, FaMapPin, FaMapSigns, FaMicrophone,
    FaMicrophoneSlash, FaMoneyBillAlt, FaMoneyBillWave, FaMoneyBillWaveAlt,
    FaMoneyCheck, FaMoneyCheckAlt, FaMouse, FaMousePointer, FaNewspaper,
    FaPalette, FaPaperPlane, FaPaperclip, FaPaste, FaPen, FaPenAlt, FaPenFancy,
    FaPenNib, FaPencilAlt, FaPercent, FaPhoneAlt, FaPhoneSlash, FaPhoneSquare,
    FaPhoneSquareAlt, FaPhoneVolume, FaPiggyBank, FaPizzaSlice, FaPlaceOfWorship,
    FaPlaneArrival, FaPlaneDeparture, FaPlug, FaPlusCircle, FaPlusSquare,
    FaPodcast, FaPoll, FaPollH, FaPortrait, FaPoundSign, FaPowerOff,
    FaPrint, FaProjectDiagram, FaPuzzlePiece, FaQrcode, FaQuestion,
    FaQuestionCircle, FaQuoteLeft, FaQuoteRight, FaReceipt, FaRedo,
    FaRedoAlt, FaRegistered, FaReply, FaReplyAll, FaRetweet, FaRibbon,
    FaRoad, FaRobot, FaRocket, FaRoute, FaRss, FaRssSquare, FaRubleSign,
    FaRuler, FaRulerCombined, FaRulerHorizontal, FaRulerVertical,
    FaRunning, FaRupeeSign, FaSatellite, FaSatelliteDish, FaSave as FaSave2,
    FaSchool, FaScrewdriver, FaScroll, FaSdCard, FaSearchDollar,
    FaSearchLocation, FaSearchMinus, FaSearchPlus, FaSeedling, FaServer,
    FaShapes, FaShareAlt, FaShareAltSquare, FaShareSquare, FaShekelSign,
    FaShieldAlt as FaShieldAlt2, FaShip as FaShip2, FaShippingFast,
    FaShoePrints, FaShoppingBag, FaShoppingBasket, FaShoppingCart as FaShoppingCart2,
    FaShower, FaShuttleVan, FaSign, FaSignInAlt, FaSignLanguage,
    FaSignOutAlt, FaSignal, FaSignature, FaSimCard, FaSitemap,
    FaSkull, FaSkullCrossbones, FaSlash, FaSleigh, FaSlidersH,
    FaSmile, FaSmileBeam, FaSmileWink, FaSmog, FaSmoking, FaSmokingBan,
    FaSms, FaSnowboarding, FaSnowflake, FaSnowman, FaSnowplow, FaSocks,
    FaSolarPanel, FaSort, FaSortAlphaDown, FaSortAlphaDownAlt,
    FaSortAlphaUp, FaSortAlphaUpAlt, FaSortAmountDown, FaSortAmountDownAlt,
    FaSortAmountUp, FaSortAmountUpAlt, FaSortDown, FaSortNumericDown,
    FaSortNumericDownAlt, FaSortNumericUp, FaSortNumericUpAlt, FaSortUp,
    FaSpa, FaSpaceShuttle, FaSpeakap, FaSpeakerDeck, FaSpellCheck,
    FaSpider, FaSpinner, FaSplotch, FaSprayCan, FaSquare, FaSquareFull,
    FaStamp, FaStar as FaStar2, FaStarAndCrescent, FaStarHalf,
    FaStarHalfAlt, FaStarOfDavid, FaStarOfLife, FaStepBackward,
    FaStepForward, FaStethoscope, FaStickyNote, FaStop as FaStop2,
    FaStopCircle, FaStopwatch, FaStore, FaStoreAlt, FaStream,
    FaStreetView, FaStrikethrough, FaStroopwafel, FaSubscript,
    FaSubway as FaSubway2, FaSuitcase, FaSuitcaseRolling, FaSun,
    FaSuperscript, FaSurprise, FaSwatchbook, FaSwimmer, FaSwimmingPool,
    FaSync, FaSyncAlt, FaSyringe, FaTable, FaTableTennis, FaTablet,
    FaTabletAlt as FaTabletAlt2, FaTablets, FaTachometerAlt, FaTag,
    FaTags, FaTape, FaTasks, FaTaxi, FaTeeth, FaTeethOpen,
    FaTelegram, FaTelegramPlane, FaTemperatureHigh, FaTemperatureLow,
    FaTenge, FaTerminal, FaTextHeight, FaTextWidth, FaTh, FaThLarge,
    FaThList, FaTheaterMasks, FaThermometer, FaThermometerEmpty,
    FaThermometerFull, FaThermometerHalf, FaThermometerQuarter,
    FaThermometerThreeQuarters, FaThumbsDown as FaThumbsDown2,
    FaThumbsUp as FaThumbsUp2, FaThumbtack, FaTicketAlt, FaTimes as FaTimes2,
    FaTimesCircle, FaTint, FaTintSlash, FaTired, FaToggleOff,
    FaToggleOn, FaToilet, FaToiletPaper, FaToolbox, FaTools,
    FaTooth, FaTorah, FaToriiGate, FaTractor, FaTrademark,
    FaTrafficLight, FaTrailer, FaTrain as FaTrain2, FaTram,
    FaTransgender, FaTransgenderAlt, FaTrash as FaTrash2, FaTrashAlt,
    FaTrashRestore, FaTrashRestoreAlt, FaTree, FaTrophy as FaTrophy2,
    FaTruck as FaTruck2, FaTruckLoading, FaTruckMonster, FaTruckMoving,
    FaTruckPickup, FaTshirt, FaTty, FaTv as FaTv2,
    FaTwitch, FaTwitter, FaTwitterSquare, FaTypo3, FaUber,
    FaUbuntu, FaUmbrella, FaUmbrellaBeach, FaUnderline, FaUndo,
    FaUndoAlt, FaUniregistry, FaUnity, FaUniversalAccess, FaUnlock as FaUnlock2,
    FaUnlockAlt, FaUntappd, FaUpload as FaUpload2, FaUps, FaUsb,
    FaUser as FaUser2, FaUserAlt, FaUserAltSlash, FaUserAstronaut,
    FaUserCheck, FaUserCircle, FaUserClock, FaUserCog, FaUserEdit,
    FaUserFriends, FaUserGraduate, FaUserInjured, FaUserLock,
    FaUserMd, FaUserMinus, FaUserNinja, FaUserNurse, FaUserPlus,
    FaUserSecret, FaUserShield, FaUserSlash, FaUserTag, FaUserTie,
    FaUserTimes, FaUsers as FaUsers2, FaUsersCog, FaUsps, FaUssunnah,
    FaUtensils as FaUtensils2, FaVaadin, FaVectorSquare, FaVenus,
    FaVenusDouble, FaVenusMars, FaViacoin, FaViadeo, FaViadeoSquare,
    FaVial, FaVials, FaViber, FaVideo as FaVideo2, FaVideoSlash,
    FaVihara, FaVimeo, FaVimeoSquare, FaVimeoV, FaVine, FaVk,
    FaVnv, FaVoicemail, FaVolleyballBall, FaVolumeDown, FaVolumeMute,
    FaVolumeOff, FaVolumeUp, FaVoteYea, FaVrCardboard, FaVuejs,
    FaWalking as FaWalking2, FaWallet as FaWallet2, FaWarehouse,
    FaWater, FaWaveSquare, FaWaze, FaWeebly, FaWeibo, FaWeight,
    FaWeightHanging, FaWeixin, FaWhatsapp, FaWhatsappSquare,
    FaWheelchair as FaWheelchair2, FaWhmcs, FaWifi as FaWifi2,
    FaWikipediaW, FaWind, FaWindowClose, FaWindowMaximize,
    FaWindowMinimize, FaWindowRestore, FaWindows, FaWineBottle,
    FaWineGlass, FaWineGlassAlt, FaWix, FaWizardsOfTheCoast,
    FaWolfPackBattalion, FaWonSign, FaWordpress, FaWordpressSimple,
    FaWpbeginner, FaWpexplorer, FaWpforms, FaWpressr, FaWrench,
    FaXRay, FaXbox, FaXing, FaXingSquare, FaYCombinator,
    FaYahoo, FaYammer, FaYandex, FaYandexInternational, FaYarn,
    FaYelp, FaYenSign, FaYinYang, FaYoutube, FaYoutubeSquare,
    FaZhihu
} from "react-icons/fa";
import { 
    Folder, FileText, LayoutDashboard, ShoppingCart, Package, Factory, Boxes, Wallet,
    Users, User, Building, GitBranch, Bell, Megaphone, DollarSign, Calendar, Layout,
    CheckSquare, FolderKanban, UserPlus, Scale, FileSignature, BookOpen, File,
    Briefcase, Target, Flag, Map, Contact, Building2, Coffee, Truck, Plane,
    ArrowRightLeft, CheckCircle, FlaskConical, TrendingUp, CreditCard, BarChart, Repeat,
    Tag, Beaker, Plug
} from "lucide-react";

export const ICON_MAP: { [key: string]: React.ComponentType<{ className?: string }> } = {
    // FontAwesome Original Set
    FaHome, FaUser, FaCog, FaChartBar, FaShoppingCart, FaBox, FaFileAlt,
    FaUsers, FaShieldAlt, FaLock, FaUnlock, FaKey, FaBell, FaSearch,
    FaCalendar, FaClock, FaEnvelope, FaPhone, FaMapMarkerAlt, FaCamera,
    FaImage, FaVideo, FaMusic, FaPlay, FaPause, FaStop, FaStar, FaHeart,
    FaThumbsUp, FaThumbsDown, FaCheck, FaTimes, FaPlus, FaMinus, FaEquals,
    FaArrowRight, FaArrowLeft, FaArrowUp, FaArrowDown, FaChevronRight,
    FaChevronLeft, FaChevronUp, FaChevronDown, FaBars, FaEllipsisH,
    FaEllipsisV, FaTrash, FaEdit, FaSave, FaDownload, FaUpload, FaShare,
    FaExternalLinkAlt, FaLink, FaUnlink, FaGlobe, FaWifi, FaBatteryFull,
    FaDesktop, FaLaptop, FaMobileAlt, FaTabletAlt, FaTv, FaBook, FaBookmark,
    FaBriefcase, FaBuilding, FaCar, FaTruck, FaPlane, FaShip, FaSubway,
    FaTrain, FaBicycle, FaWalking, FaWheelchair, FaBed, FaHotel, FaCoffee,
    FaUtensils, FaBeer, FaGlassCheers, FaBirthdayCake, FaGift, FaTrophy,
    FaMedal, FaCrown, FaMoneyBill, FaCreditCard, FaWallet, FaDollarSign,

    // Extended Business Set (deduplicated where necessary in key map)
    FaHandshake, FaChartLine, FaChartPie, FaChartArea, FaBalanceScale,
    FaBullhorn, FaBullseye, FaCalculator, FaCalendarCheck, FaCalendarPlus,
    FaCertificate, FaClipboard, FaClipboardList, FaClipboardCheck, FaCoins,
    FaComment, FaCommentDots, FaComments, FaCompass, FaCopy, FaCopyright,
    FaDatabase, FaDirections, FaFile, FaFileArchive, FaFileAudio, FaFileCode,
    FaFileContract, FaFileCsv, FaFileDownload, FaFileExcel, FaFileExport,
    FaFileImage, FaFileImport, FaFileInvoice, FaFileInvoiceDollar, FaFilePdf,
    FaFilePowerpoint, FaFilePrescription, FaFileSignature, FaFileUpload,
    FaFileVideo, FaFileWord, FaFingerprint, FaFlag, FaFolder, FaFolderOpen,
    FaFolderPlus, FaFolderMinus, FaGavel, FaGem, FaGlobeAmericas, FaGlobeAsia,
    FaGlobeEurope, FaHeadset, FaHistory, FaHourglass, FaHourglassEnd,
    FaHourglassHalf, FaHourglassStart, FaIdBadge, FaIdCard,
    FaInbox, FaIndustry, FaInfo, FaInfoCircle, FaKeyboard,
    FaLandmark, FaLayerGroup, FaLeaf, FaList, FaListAlt, FaListOl, FaListUl,
    FaMap, FaMapMarked, FaMapMarkedAlt, FaMapPin, FaMapSigns, FaMicrophone,
    FaMicrophoneSlash, FaMoneyBillAlt, FaMoneyBillWave, FaMoneyBillWaveAlt,
    FaMoneyCheck, FaMoneyCheckAlt, FaMouse, FaMousePointer, FaNewspaper,
    FaPalette, FaPaperPlane, FaPaperclip, FaPaste, FaPen, FaPenAlt, FaPenFancy,
    FaPenNib, FaPencilAlt, FaPercent, FaPhoneAlt, FaPhoneSlash, FaPhoneSquare,
    FaPhoneSquareAlt, FaPhoneVolume, FaPiggyBank, FaPizzaSlice, FaPlaceOfWorship,
    FaPlaneArrival, FaPlaneDeparture, FaPlug, FaPlusCircle, FaPlusSquare,
    FaPodcast, FaPoll, FaPollH, FaPortrait, FaPoundSign, FaPowerOff,
    FaPrint, FaProjectDiagram, FaPuzzlePiece, FaQrcode, FaQuestion,
    FaQuestionCircle, FaQuoteLeft, FaQuoteRight, FaReceipt, FaRedo,
    FaRedoAlt, FaRegistered, FaReply, FaReplyAll, FaRetweet, FaRibbon,
    FaRoad, FaRobot, FaRocket, FaRoute, FaRss, FaRssSquare, FaRubleSign,
    FaRuler, FaRulerCombined, FaRulerHorizontal, FaRulerVertical,
    FaRunning, FaRupeeSign, FaSatellite, FaSatelliteDish,
    FaSchool, FaScrewdriver, FaScroll, FaSdCard, FaSearchDollar,
    FaSearchLocation, FaSearchMinus, FaSearchPlus, FaSeedling, FaServer,
    FaShapes, FaShareAlt, FaShareAltSquare, FaShareSquare, FaShekelSign,
    FaShippingFast,
    FaShoePrints, FaShoppingBag, FaShoppingBasket,
    FaShower, FaShuttleVan, FaSign, FaSignInAlt, FaSignLanguage,
    FaSignOutAlt, FaSignal, FaSignature, FaSimCard, FaSitemap,
    FaSkull, FaSkullCrossbones, FaSlash, FaSleigh, FaSlidersH,
    FaSmile, FaSmileBeam, FaSmileWink, FaSmog, FaSmoking, FaSmokingBan,
    FaSms, FaSnowboarding, FaSnowflake, FaSnowman, FaSnowplow, FaSocks,
    FaSolarPanel, FaSort, FaSortAlphaDown, FaSortAlphaDownAlt,
    FaSortAlphaUp, FaSortAlphaUpAlt, FaSortAmountDown, FaSortAmountDownAlt,
    FaSortAmountUp, FaSortAmountUpAlt, FaSortDown, FaSortNumericDown,
    FaSortNumericDownAlt, FaSortNumericUp, FaSortNumericUpAlt, FaSortUp,
    FaSpa, FaSpaceShuttle, FaSpeakap, FaSpeakerDeck, FaSpellCheck,
    FaSpider, FaSpinner, FaSplotch, FaSprayCan, FaSquare, FaSquareFull,
    FaStamp, FaStarAndCrescent, FaStarHalf,
    FaStarHalfAlt, FaStarOfDavid, FaStarOfLife, FaStepBackward,
    FaStepForward, FaStethoscope, FaStickyNote,
    FaStopCircle, FaStopwatch, FaStore, FaStoreAlt, FaStream,
    FaStreetView, FaStrikethrough, FaStroopwafel, FaSubscript,
    FaSuitcase, FaSuitcaseRolling, FaSun,
    FaSuperscript, FaSurprise, FaSwatchbook, FaSwimmer, FaSwimmingPool,
    FaSync, FaSyncAlt, FaSyringe, FaTable, FaTableTennis, FaTablet,
    FaTablets, FaTachometerAlt, FaTag,
    FaTags, FaTape, FaTasks, FaTaxi, FaTeeth, FaTeethOpen,
    FaTelegram, FaTelegramPlane, FaTemperatureHigh, FaTemperatureLow,
    FaTenge, FaTerminal, FaTextHeight, FaTextWidth, FaTh, FaThLarge,
    FaThList, FaTheaterMasks, FaThermometer, FaThermometerEmpty,
    FaThermometerFull, FaThermometerHalf, FaThermometerQuarter,
    FaThermometerThreeQuarters,
    FaThumbtack, FaTicketAlt,
    FaTimesCircle, FaTint, FaTintSlash, FaTired, FaToggleOff,
    FaToggleOn, FaToilet, FaToiletPaper, FaToolbox, FaTools,
    FaTooth, FaTorah, FaToriiGate, FaTractor, FaTrademark,
    FaTrafficLight, FaTrailer, FaTram,
    FaTransgender, FaTransgenderAlt, FaTrashAlt,
    FaTrashRestore, FaTrashRestoreAlt, FaTree,
    FaTruckLoading, FaTruckMonster, FaTruckMoving,
    FaTruckPickup, FaTshirt, FaTty,
    FaTwitch, FaTwitter, FaTwitterSquare, FaTypo3, FaUber,
    FaUbuntu, FaUmbrella, FaUmbrellaBeach, FaUnderline, FaUndo,
    FaUndoAlt, FaUniregistry, FaUnity, FaUniversalAccess,
    FaUnlockAlt, FaUntappd, FaUps, FaUsb,
    FaUserAlt, FaUserAltSlash, FaUserAstronaut,
    FaUserCheck, FaUserCircle, FaUserClock, FaUserCog, FaUserEdit,
    FaUserFriends, FaUserGraduate, FaUserInjured, FaUserLock,
    FaUserMd, FaUserMinus, FaUserNinja, FaUserNurse, FaUserPlus,
    FaUserSecret, FaUserShield, FaUserSlash, FaUserTag, FaUserTie,
    FaUserTimes, FaUsersCog, FaUsps, FaUssunnah,
    FaVaadin, FaVectorSquare, FaVenus,
    FaVenusDouble, FaVenusMars, FaViacoin, FaViadeo, FaViadeoSquare,
    FaVial, FaVials, FaViber, FaVideoSlash,
    FaVihara, FaVimeo, FaVimeoSquare, FaVimeoV, FaVine, FaVk,
    FaVnv, FaVoicemail, FaVolleyballBall, FaVolumeDown, FaVolumeMute,
    FaVolumeOff, FaVolumeUp, FaVoteYea, FaVrCardboard, FaVuejs,
    FaWarehouse,
    FaWater, FaWaveSquare, FaWaze, FaWeebly, FaWeibo, FaWeight,
    FaWeightHanging, FaWeixin, FaWhatsapp, FaWhatsappSquare,
    FaWhmcs,
    FaWikipediaW, FaWind, FaWindowClose, FaWindowMaximize,
    FaWindowMinimize, FaWindowRestore, FaWindows, FaWineBottle,
    FaWineGlass, FaWineGlassAlt, FaWix, FaWizardsOfTheCoast,
    FaWolfPackBattalion, FaWonSign, FaWordpress, FaWordpressSimple,
    FaWpbeginner, FaWpexplorer, FaWpforms, FaWpressr, FaWrench,
    FaXRay, FaXbox, FaXing, FaXingSquare, FaYCombinator,
    FaYahoo, FaYammer, FaYandex, FaYandexInternational, FaYarn,
    FaYelp, FaYenSign, FaYinYang, FaYoutube, FaYoutubeSquare,
    FaZhihu,

    // Lucide Defaults
    Folder, FileText, LayoutDashboard, ShoppingCart, Package, Factory, Boxes, Wallet,
    Users, User, Building, GitBranch, Bell, Megaphone, DollarSign, Calendar, Layout,
    CheckSquare, FolderKanban, UserPlus, Scale, FileSignature, BookOpen, File,
    Briefcase, Target, Flag, Map, Contact, Building2, Coffee, Truck, Plane,
    ArrowRightLeft, CheckCircle, FlaskConical, TrendingUp, CreditCard, BarChart, Repeat,
    Tag, Beaker, Plug
};

export const iconNames = Object.keys(ICON_MAP);
